export const FOLDERS = [
    {
        iconId:   'open-projects',
        windowId: 'projects-window',
        title:    'Projects',
        icon:     '📁',
        path:     'vskid/Projects',
        items: [
            {
                type:  'project',
                icon:  '🔗',
                name:  'Momentum',
                date:  '21 - 02 - 2026',
                href:  'https://github.com/notifications-star/lifeos',
            },
        ],
    },
    {
        iconId:   'open-videos',
        windowId: 'videos-window',
        title:    'Videos',
        icon:     '🎬',
        path:     'vskid/Videos',
        items: [
            {
                type:  'video',
                icon:  '🎬',
                name:  'Important Message!',
                date:  '25 - 10 - 1987',
                id:    'dQw4w9WgXcQ',
                title: 'Important Message!',
            },
            {
                type:  'video',
                icon:  '🎬',
                name:  'Man Plays Saxophone',
                date:  '25 - 10 - 1987',
                id:    '/videos/Video-by-perrellcpt-_IG_p_Cw4C7cMsL76_-copy.webm',
                title: 'Man Plays Saxophone',
            },
            {
                type:  'video',
                icon:  '🎬',
                name:  'National Anthem',
                date:  '27 - 02 - 2020',
                id:    'WyKAZt27A9w',
                title: 'National Anthem',
            },
            {
                type:  'video',
                icon:  '🎬',
                name:  'Video Taken 2001',
                date:  '11 - 09 - 2001',
                id:    '/videos/nokiavideotest.webm',
                title: 'Video Taken 2001',
            },
        ],
    },
    {
        iconId:   'open-music',
        windowId: 'music-window',
        title:    'Music',
        icon:     '🎵',
        path:     'vskid/Music',
        items: [
            {
                type:  'audio',
                icon:  '🎧',
                name:  'Sandstorm',
                date:  '25 - 02 - 2026',
                src:   '/music/Darude - Sandstorm.mp3',
                title: 'Darude - Sandstorm',
            },
            {
                type:  'audio',
                icon:  '🎧',
                name:  'Kalimba (Ninja Tuna)',
                date:  '25 - 02 - 2026',
                src:   '/music/Mr Scruff - Kalimba (Ninja Tuna).mp3',
                title: 'Mr Scruff - Kalimba (Ninja Tuna)',
            },
            {
                type:  'audio',
                icon:  '🎧',
                name:  'Joan Progression',
                date:  '25 - 02 - 2026',
                src:   '/music/chordtest joanprog.mp3',
                title: 'Joan Progression',
            },
            {
                type:  'audio',
                icon:  '🎧',
                name:  'McDonalds beat',
                date:  '17 - 11 - 2024',
                src:   '/music/mcd cook 17 11 2024.mp3',
                title: 'McDonalds beat 17 - 11 - 2024',
            },
            {
                type:  'audio',
                icon:  '🎧',
                name:  'TB-303 test',
                date:  '25 - 02 - 2026',
                src:   '/music/tb303 test.mp3',
                title: 'TB-303 test',
            },
            {
                type:  'audio',
                icon:  '🎧',
                name:  'Test Project #1',
                date:  '25 - 02 - 2026',
                src:   '/music/Testproj1.mp3',
                title: 'Test Project #1',
            },
            {
                type:  'audio',
                icon:  '🎧',
                name:  'Test Project #2',
                date:  '25 - 02 - 2026',
                src:   '/music/testproj2.mp3',
                title: 'Test Project #2',
            },
        ],
    },
    {
        iconId:   'open-pictures',
        windowId: 'pictures-window',
        title:    'Pictures',
        icon:     '🖼️',
        path:     'vskid/Pictures',
        items: [
            {
                type:  'image',
                icon:  '🖼️',
                name:  'Example',
                date:  '01 - 01 - 2025',
                src:   'https://upload.wikimedia.org/wikipedia/commons/b/b8/Loss.svg',
                title: 'Example Image',
            },
            {
                type:  'image',
                icon:  '🖼️',
                name:  'Test Image',
                date:  '01 - 01 - 2025',
                src:   'https://upload.wikimedia.org/wikipedia/en/7/73/Trollface.png',
                title: 'Test Image',
            },
        ],
    },
    {
        iconId:   'open-docs',
        windowId: 'docs-window',
        title:    'Documents',
        icon:     '📄',
        path:     'vskid/Documents',
        items: [
            { 
                type:'doc', 
                icon:'📄', 
                name:'Hello World', 
                date:'25 - 02 - 2025',
                id:'hello-world', 
                title:'Hello World' 
            },
        ],
    },
];

export const BLOG_POSTS = [
     {
         id:      'hello-world',
         title:   'Hello World',
         date:    '01 - 01 - 2025',
         summary: 'My first post.',
         file:    'posts/hello-world.md',
     },
];

export const WALL_PASSWORD = 'John 3:16';